import html2canvas from "html2canvas";

function downloadDataUrl(filename: string, dataUrl: string) {
  const a = document.createElement("a");
  a.href = dataUrl;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
}

function fallbackSvgDownload(container: HTMLElement, filenameBase: string) {
  const svg = container.querySelector("svg");
  if (!svg) return;
  const serializer = new XMLSerializer();
  const svgText = serializer.serializeToString(svg);
  const dataUrl = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svgText)}`;
  downloadDataUrl(`${filenameBase}.svg`, dataUrl);
}

function findSnapshotRoot(node: HTMLElement): HTMLElement {
  let current: HTMLElement | null = node;
  while (current && current !== document.body) {
    const cls = String(current.className || "");
    // Card root generated by our shared Card component.
    if (cls.includes("rounded-lg") && cls.includes("bg-card") && cls.includes("shadow-sm")) {
      return current;
    }
    current = current.parentElement;
  }
  return node;
}

export async function saveChartSnapshot(containerId: string, filenameBase: string) {
  const source = document.getElementById(containerId);
  if (!source) return;
  const container = findSnapshotRoot(source);

  try {
    const canvas = await html2canvas(container, {
      backgroundColor: "#ffffff",
      scale: Math.max(2, Math.min(3, window.devicePixelRatio || 2)),
      useCORS: true,
      allowTaint: true,
      logging: false,
    });
    const pngDataUrl = canvas.toDataURL("image/png");
    downloadDataUrl(`${filenameBase}.png`, pngDataUrl);
  } catch {
    fallbackSvgDownload(container, filenameBase);
  }
}
